kind: Deployment
apiVersion: apps/v1
metadata:
  name: xwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xwiki-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xwiki-app
    spec:
      volumes:
        - name: xwiki-vol
          persistentVolumeClaim:
            claimName: xwiki
      containers:
        - name: xwiki-app-instance
          image: 'xwiki:stable'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: xwiki
                  key: DB_DATABASE
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: xwiki
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xwiki
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: xwiki
                  key: DB_USER
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: xwiki-vol
              mountPath: /usr/local/xwiki          
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
